#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <algorithm>
#include <optional>
#include <memory>
#include <regex>
#include <concepts>
#include <type_traits>
#include <cmath>
#include <cstdlib>
#include <cstdio>
#include <chrono>
#include <format>
#include <variant>
#include <filesystem>
#include <fstream>
#include <sstream>