#pragma once
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdint>
#include <limits>
#include <vector>
#include <type_traits>
#include <array>
#include <map>
#include <unordered_map>
#include <variant>
#include <optional>
#include <functional>
#include <memory>
#include <utility>
#include <format>
#include <regex>
#include <random>
#include <ctime>
